language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.6
  - 2.3.3
  - ruby-head

gemfile:
  - gemfiles/activesupport_42.gemfile
  - gemfiles/activesupport_50.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activesupport_50.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activesupport_50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activesupport_50.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/activesupport_42.gemfile
  include:
    - rvm: jruby-9.1.5.0
      gemfile: gemfiles/activesupport_42.gemfile
      jdk: oraclejdk8
    - rvm: jruby-9.1.5.0
      gemfile: gemfiles/activesupport_50.gemfile
      jdk: oraclejdk8
    - rvm: jruby-head
      gemfile: gemfiles/activesupport_42.gemfile
      jdk: oraclejdk8
    - rvm: jruby-head
      gemfile: gemfiles/activesupport_50.gemfile
      jdk: oraclejdk8

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
  fast_finish: true

before_install: gem install bundler -v 1.13.6

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter

