language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - ruby-head

gemfile:
  - gemfiles/activesupport_42.gemfile
  - gemfiles/activesupport_50.gemfile
  - gemfiles/activesupport_51.gemfile
  - gemfiles/activesupport_edge.gemfile

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/activesupport_42.gemfile
  include:
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/activesupport_42.gemfile
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/activesupport_50.gemfile
      jdk: oraclejdk8
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/activesupport_51.gemfile
      jdk: oraclejdk8
    - rvm: jruby-head
      gemfile: gemfiles/activesupport_42.gemfile
      jdk: oraclejdk8
    - rvm: jruby-head
      gemfile: gemfiles/activesupport_50.gemfile
      jdk: oraclejdk8
    - rvm: jruby-head
      gemfile: gemfiles/activesupport_51.gemfile
      jdk: oraclejdk8

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.8.0
    - rvm: jruby-head
  fast_finish: true

before_install: gem install bundler -v 1.14.6

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
